services:
  backend:
    build: .
    container_name: sentinel_backend
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/sentinel
      - MQTT_HOST=mosquitto
    ports: ["8000:8000"]
    volumes:
      - .:/code
      - backend_venv:/code/.venv
    depends_on:
      - db
      - mosquitto

  frontend:
    build: ./frontend
    container_name: sentinel_frontend
    env_file: frontend/.env
    environment:
      - VITE_PROXY_TARGET=http://backend:8000
    ports: ["80:5173"]
    volumes:
      - ./frontend:/code
      - frontend_node_modules:/code/node_modules
    depends_on:
      - backend

  db:
    image: timescale/timescaledb:2.26.3-pg18
    container_name: sentinel_db
    environment:
      - POSTGRES_DB=sentinel
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    ports: ["1883:1883"]
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:
  backend_venv:
  frontend_node_modules:
