"""Replace telemetry with climate readings

Revision ID: 98e6c996836c
Revises: adf1f525ddb3
Create Date: 2026-07-15 15:02:22.994264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98e6c996836c'
down_revision: Union[str, Sequence[str], None] = 'adf1f525ddb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('location_snapshot', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id', 'timestamp')
    )
    op.drop_table('telemetry_data')
    # ### end Alembic commands ###
   
    # Create timescaleDB hypertable
    op.execute("SELECT create_hypertable('climate_readings', 'timestamp', if_not_exists => TRUE);")

    # Continuous aggregates can't be created inside a transaction block, so run
    # them in an autocommit block (same pattern as CREATE INDEX CONCURRENTLY).
    with op.get_context().autocommit_block():
        op.execute("""
            CREATE MATERIALIZED VIEW climate_5m WITH (timescaledb.continuous) AS
            SELECT time_bucket('5 minutes', timestamp) AS bucket,
                   device_id, AVG(temperature) AS temperature,
                   AVG(humidity) AS humidity, AVG(pressure) AS pressure,
                   location_snapshot
            FROM climate_readings
            GROUP BY bucket, device_id, location_snapshot;
        """)

        op.execute("""
            CREATE MATERIALIZED VIEW climate_1h WITH (timescaledb.continuous) AS
            SELECT time_bucket('1 hour', timestamp) AS bucket,
                   device_id, AVG(temperature) AS temperature,
                   AVG(humidity) AS humidity, AVG(pressure) AS pressure,
                   location_snapshot
            FROM climate_readings
            GROUP BY bucket, device_id, location_snapshot;
        """)

        # Keep aggregates refreshed automatically on a schedule.
        op.execute("""
            SELECT add_continuous_aggregate_policy('climate_5m',
                start_offset => INTERVAL '1 hour',
                end_offset => INTERVAL '5 minutes',
                schedule_interval => INTERVAL '5 minutes');
        """)

        op.execute("""
            SELECT add_continuous_aggregate_policy('climate_1h',
                start_offset => INTERVAL '3 days',
                end_offset => INTERVAL '1 hour',
                schedule_interval => INTERVAL '1 hour');
        """)

        # Retention: raw data is kept for 7 days, 5-minute rollups pick up
        # where raw data is dropped and are kept for 30 days total,
        # and hourly rollups are kept indefinitely.
        op.execute("""
            SELECT add_retention_policy('climate_readings', drop_after => INTERVAL '7 days');
        """)

        op.execute("""
            SELECT add_retention_policy('climate_5m', drop_after => INTERVAL '30 days');
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop continuous aggregates in an autocommit block (can't run in a transaction).
    with op.get_context().autocommit_block():
        op.execute("DROP MATERIALIZED VIEW IF EXISTS climate_1h CASCADE;")
        op.execute("DROP MATERIALIZED VIEW IF EXISTS climate_5m CASCADE;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_data',
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metric', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('location_snapshot', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('telemetry_data_device_id_fkey')),
    sa.PrimaryKeyConstraint('timestamp', 'device_id', 'metric', name=op.f('telemetry_data_pkey'))
    )
    op.drop_table('climate_readings')
    # ### end Alembic commands ###
