"""added_location

Revision ID: adf1f525ddb3
Revises: cd98b861089c
Create Date: 2026-05-04 20:00:00.287038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf1f525ddb3'
down_revision: Union[str, Sequence[str], None] = 'cd98b861089c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE telemetry_data CASCADE")
    op.execute("TRUNCATE TABLE devices CASCADE")
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.add_column('devices', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key('location_id_fkey', 'devices', 'locations', ['location_id'], ['id'])
    op.drop_column('devices', 'location')
    op.add_column('telemetry_data', sa.Column('location_snapshot', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry_data', 'location_snapshot')
    op.add_column('devices', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint('location_id_fkey', 'devices', type_='foreignkey')
    op.drop_column('devices', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
