"""initial_schema

Revision ID: b5e4e388de4e
Revises: 
Create Date: 2026-05-02 14:12:21.900073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e4e388de4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hardware_id', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'BLOCKED', name='devicestatus'), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_hardware_id'), 'devices', ['hardware_id'], unique=True)
    op.create_table('telemetry_data',
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'device_id', 'metric')
    )
    op.execute("SELECT create_hypertable('telemetry_data', 'timestamp');")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_data')
    op.drop_index(op.f('ix_devices_hardware_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
